### PR TITLE
Add detailsand form

### PR DESCRIPTION
**Pull request by Showcode24**
### Add Details and Form
1. Implemented useParams function
2. Created forms

### CODE REVIEW

**Review by Bestbynature — CHANGES_REQUESTED** [review]
Almost There GIF

Hello @Showcode24. Thank you so much for your submission. Your app is working fine and contains no error. 

However, you need to update the navbar component to include a link that will take users to '/create', which will now load the form that you have created.

When you do that, please push the code to this same branch and resubmit the link to this same pull request.

Don't create another PULL REQUEST, Please

**Comment by Showcode24** [comment]
Ok sir

**Review by Bestbynature — APPROVED** [review]
Congratulations @Showcode24 

# APPROVED 🥇 

Please merge and move to the next milestone

**Comment by Showcode24** [comment]
Thank you sir

**Pull request merged**
